# Generated by Django 6.0.5 on 2026-05-19 12:10

from django.db import migrations, models


def copy_formation_to_formations(apps, schema_editor):
    Etudiant = apps.get_model('etudiants', 'Etudiant')

    for etudiant in Etudiant.objects.exclude(formation=None):
        etudiant.formations.add(etudiant.formation)


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='formations',
            field=models.ManyToManyField(blank=True, to='formations.formation'),
        ),
        migrations.RunPython(copy_formation_to_formations, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='etudiant',
            name='formation',
        ),
    ]
